### ISSUE TITLE
Config Loader for login action

### ISSUE THREAD

**Issue by aaronjsutton** [aaronjsutton/DarkSpeed-Server#4]
Using a YAML file located at `config/darksocks.yml`, formatted like so:
```yaml
gateway:
  port: 4728
  password: gateway

main:
  port: 8008
  password: super_secret
```
Ruby Standard Library has support for YAML parsing, like JSON. 

Inside the `login` method, parse this YAML file, then place the port and password of main into a Hash, and call `render json:` to place these settings into the response body. The code that parses the YAML would best be inside it’s own method that returns the hash, then called from `login`. 

Make sure to replace `head :accepted` with `response.status = :accepted` to avoid a double render call. 

Cheers
